### ISSUE TITLE
Error with 3_run_predicttargets.sh shell script

### ISSUE THREAD

**Issue by cedunia** [fschmich/tscan_wrapper#1]
I'm so interest by your wrapper and gespeR for my own HCS analysis.
I've got this error when i run 3_run_predicttargets.sh
Traceback (most recent call last):
  File "predicttargets.py", line 178, in <module>
    main()
  File "predicttargets.py", line 166, in main
    targets = parse(contextplus_score_file)
  File "predicttargets.py", line 94, in parse
    csf = open(csfile, "r")
IOError: [Errno 2] No such file or directory: '/tmp/cps_qT_cLs'
hassen-khodja@phoenix:~/Documents/Projet HSC/OTEs/tscan_wrapper-master$ ./3_run_predicttargets.sh
s223211: AAAAUACAACUGGAGAUGGag
Can you help me to debug this error ?

**Comment by cedunia** [comment]
A new version TargetScan 7.0 explain this bug
